### ISSUE TITLE
I'm having deployment issues 

### ISSUE THREAD

**Issue by SleepyBiscuits** [Ulziitugsa/Tafe20S202#2]
![image](https://user-images.githubusercontent.com/67183399/92212219-cb525400-eed0-11ea-9d28-9f3671b8484b.png)

**Comment by jackchurch** [comment]
Hi DeliciousBiscuits, 

Applications are unable to run on file systems that are formatted as exFat. This is unfortunately a limitation of Microsoft Windows. 

To get the program to run, please move the files onto a hard disk that is formatted with NTFS. 

Please let me know if you require any more help with this. 

Regards
Jack

**Comment by SleepyBiscuits** [comment]
Hi Jack 

Thank you, The application started running when I reformatted the hard disk to NTFS just like you said. 

Regards,
Kizzie

**Comment by Ulziitugsa** [comment]
Good job peopleeeee
